---
# tasks file for squad-server

- name: Deploy Configs
  ansible.builtin.include_tasks: deploy-configs.yml
  when: squad_deploy_configs | bool

- name: Start Squad Server or Restart if Started
  block:
    - name: Ensure Python3 and Python3 Pip Are Installed
      become: true
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Ensure docker For Python is Installed
      ansible.builtin.pip:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
      loop:
        - name: docker
          version: 6.0.1

        - name: docker-compose
          version: 1.29.2

    - name: Start Squad Server Services
      when: server.docker.name == squad_server_to_restart or squad_restart_all | bool
      community.docker.docker_compose:
        project_src: "{{ squad_servers_dir }}"
        pull: true
        services:
          - "squad-{{ server.docker.name }}"
          - "squadjs-{{ server.docker.name }}"
        state: present
        restarted: true
      loop: "{{ squad_servers }}"
      loop_control:
        label: "SQUAD SERVER -> {{ server.name }}"
        loop_var: server


    - name: Start Only Squadjs Server Services
      when: server.docker.name == squadjs_to_restart or squadjs_restart_all | bool
      community.docker.docker_compose:
        project_src: "{{ squad_servers_dir }}"
        pull: true
        services:
          - "squadjs-{{ server.docker.name }}"
        state: present
        restarted: true
      loop: "{{ squad_servers }}"
      loop_control:
        label: "SQUADJS -> {{ server.name }}"
        loop_var: server
