---
# tasks file for squad-server

- name: Deploy Configs
  ansible.builtin.include_tasks: deploy-configs.yml
  when: squad_deploy_configs | bool

- name: Start Squad Server or Restart if Started
  ansible.builtin.include_tasks: start-container.yml
  when: server.docker.name == squad_server_to_restart or squad_restart_all | bool
  loop: "{{ squad_servers }}"
  loop_control:
    loop_var: server
