---
# yamllint disable rule:line-length
all:
  vars:
    server_timezone: America/Chicago
  hosts:
    asgard.orion-technologies.io:
      ansible_user: asgard
      squad_server_user: asgard
      squad_server_group: asgard
      squad_mysql:
        user: "squadjs"
        user_password: "{{ lookup('ansible.builtin.env', 'SQUAD_MYSQL_USER_PASSWORD' )}}"
        root_password: "{{ lookup('ansible.builtin.env', 'SQUAD_MYSQL_ROOT_PASSWORD' )}}"
        database: squadjs

      squad_default_settings:
        server_id: 0 # As a note, server IDs must be started at 1!
        docker:
          name: vanilla-squad
          images:
            server: squad:latest
            squadjs: squadjs:latest
        secrets:
          rcon_password: test
          squadjs_discord_token: ""
          license: ""
        groups:
          # This is for the discord admin ping
          - name: 1039155511066636329
            permissions: []
            squadjs:
              admin_ping: true

          - name: Odin
            permissions:
              - changemap
              - pause
              - balance
              - chat
              - kick
              - ban
              - cameraman
              - teamchange
              - forceteamchange
              - canseeadminchat
              - reserve
              - config
              - cheat
              - featuretest
            squadjs:
              admin_ping: false
            members:
              - name: Kinsher
                comment: Server Administrator
                steam64: 76561197986710399

              - name: Atrocity
                steam64: 76561199101367413

              - name: Xikky
                steam64: 76561198001193856

              - name: iiTherRealMcCoy
                steam64: 76561199028579724

              - name: MaxRecon
                steam64: 76561198153769543

              - name: SheHulk
                steam64: 76561198067016254

              - name: Malinoff
                steam64: 76561198404402665

              - name: Teggy
                steam64: 76561198356666755

              - name: SooperGloo
                steam64: 76561198855097026
                
              - name: wolf.rayne
                steam64: 76561198107367726

          - name: Thor
            squadjs:
              admin_ping: false
            permissions:
              - changemap
              - balance
              - chat
              - kick
              - ban
              - cameraman
              - teamchange
              - forceteamchange
              - canseeadminchat
              - reserve
            members:
              - name: Lt_Longsword
                steam64: 76561198373523022
                
              - name: Freeman
                steam64: 76561198329170534
                
              - name: Coiffee
                steam64: 76561198046579272
                
              - name: Elon
                steam64: 76561198203568744
                
              - name: Kin_Seward
                steam64: 76561198799111045
                
              - name: Chemji
                steam64: 76561199127559778
                
              - name: Skillet
                comment: promoted 04-25-23
                steam64: 76561198221715432
                
          - name: Loki
            squadjs:
              admin_ping: false
            permissions:
              - balance
              - chat
              - kick
              - ban
              - teamchange
              - canseeadminchat
              - reserve
              - cameraman
              - changemap
              - forceteamchange
            members:
              - name: Frizz
                steam64: 76561198339174737

              - name: Rabbid_Squirrel
                comment: promoted 12-26-22
                steam64: 76561198081576045
                
              - name: Madtopher
                comment: promoted 04-25-2023
                steam64: 76561199060693600
                
              - name: Dr.hammerstien
                comment: promoted 04-25-2023
                steam64: 76561198037486479
                
              - name: Rarg
                comment: promoted 4-25-2023
                steam64: 76561198073565669
                
              - name: Vaunt 
                comment: promoted 4-25-2023
                steam64: 76561198031865730
                
              - name: RIOTYouth1
                comment: Admin 4-27-2023
                steam64: 76561198209119887
                
              - name: Grand Slam AKA Val
                comment: Admin 5-9-2023
                steam64: 76561199070771491
                
              - name: Shifty
                comment: Jr Admin 4-26-2023
                steam64: 76561198251723570

              - name: VanillaForsty
                comment: Admin 06-15-2023
                steam64: 76561198383222393

              - name: Pdgeorge5
                comment: admin 06-23-2023
                steam64: 76561198010920870

          - name: Balder
            squadjs:
              admin_ping: false
            permissions:
              - balance
              - chat
              - kick
              - ban
              - teamchange
              - canseeadminchat
              - reserve
            members: 
                
              - name: Scarface
                comment: Jr Admin 5-11-2023
                steam64: 76561198312514319
                
              - name: KodakBlackrack
                comment: Jr Admmin 7-19-23
                steam64: 76561198288578416

              - name: TheToxicTanker
                comment: Jr Admin 7-19-23
                steam64: 76561199000113460

                
                
          - name: Whitelist
            permissions:
              - reserve
            members:
              - name: Treay ~ Sam
                comment: For Asgard IT Started 01/09/2023
                steam64: 76561198090760895

              - name: Gel The Doctor
                comment: Added by MaX unlimited Whitelist
                steam64: 76561198098735539

              - name: Mauro
                comment: men1995@gmail.com
                steam64: 76561198098391966

              - name: RIOTYouth1
                comment: aclerc1220@gmail.com
                steam64: 76561198209119887

              - name: "{ASG} Scarface"
                comment: logangrimes11@gmail.com
                steam64: 76561198312514319

              - name: "{ASG} young sloth"
                comment: logangrimes11@gmail.com
                steam64: 76561198983371735

              - name: Skillet
                comment: Server Administrator
                steam64: 76561198221715432

              - name: LtJamesFox
                steam64: 76561198026192477
                comment: Nevetsu@hotmail.com

              - name: tcandan88(4skin)
                comment: ducati979@aol.com
                steam64: 76561198059124010

              - name: Dick Deflator
                comment: Whitelist for 4 month's started 03/11/2023/Ends 07/11/2023
                steam64: 76561199062085282

              - name: Bagels
                comment: adroessler10@gmail.com
                steam64: 76561198059462064

              - name: Hypothermiack
                steam64: 76561198119385943

              - name: TapatioTimmy
                comment: camdenricketts4@gmail.com
                steam64: 76561199123384670

              - name: TheGoochSlooth
                comment: justintestorelli@gmail.com
                steam64: 76561199285813056

              - name: Subterfuge
                comment: jwlind@gmail.com
                steam64: 76561197963075020

              - name: Juggernaut
                comment: robledoaustin@yahoo.com
                steam64: 76561198049739312

              - name: DamiSupreme
                comment: alexdemiane93@gmail.com
                steam64: 76561197979663830

              - name: Mr_poopy_diaper
                comment: Attached to (ASG) Kybar (carbarykyle@gmail.com)
                steam64: 76561199302780874

              - name: OneBarStatus
                comment: jacobadams135@yahoo.com
                steam64: 76561198801895406

              - name: Kazy
                comment: jacobadams135@yahoo.com (Attached to OneBarStatus)
                steam64: 76561198989641003

              - name: The Half-WitViking
                comment: jacobadams135@yahoo.com (Attached to OneBarStatus)
                steam64: 76561198870442236

              - name: Warbot
                comment: imawsome404@yahoo.com - Xikky
                steam64: 76561197960350874

              - name: Duffmann9992
                comment: Attached to imawsome404@yahoo.com - xikky
                steam64: 76561197986254647

              - name: HeyWhatchaDoin
                comment: Attached to imawsome404@yahoo.com - Xikky
                steam64: 76561198405495371
                
              - name: Bowlpacks
                comment: attached to imawsome404@yahoo.com - Xikky
                steam64: 76561198054422673

              - name: BoozBear
                comment: attached to imawsome404@yahoo.com - Xikky
                steam64: 76561198940959919

              - name: dmpca
                comment: attached to imawsome404@yahoo.com - Xikky
                steam64: 76561197962791616

              - name: fonzie141
                comment: benmandino@gmail.com
                steam64: 76561198056302525
                
              - name: "Orion159044#1238 @T/5 Fairchild [29th ID]"
                comment: orionbarclay7@gmail.com
                steam64: 76561198170375391
              
              - name: "[NOT]TheSaltiestAround"
                comment: austinbuda99@gmail.com
                steam64: 76561198107206903

              - name: 1stRB NinjaOfDeath
                comment: Added by MaX
                steam64: 76561198386944513
                
              - name: Wrath
                comment:  Expires 9 9 2023
                steam64: 76561198321121244

              - name: NightsterHD
                comment:  Expires 9 9 2023
                steam64: 76561198035379744

              - name: Jagernauted
                comment:  Expires 9 9 2023
                steam64: 76561198049739312

              - name: Pharzuph
                comment:  Expires 9 9 2023
                steam64: 76561198307857974
                
        ban_urls: []
        remote_admin_hosts: []
        remote_admin_list: 
          - vanilla-autowl
          - Einherjar
          - Balder
          - Loki
          - Thor
          - LIAISON
          - ASG%20Champions%20Of%20The%20Month
          - expats
          - ASG%20Affiliates
        messages:
          - Welcome to Asgard Eternal! Remember to add Asgard to your favorites list!!
          - Check out Asgard Discord https://discord.gg/asg
        layers:
          - Gorodok_RAAS_v7
          - AlBasrah_Invasion_v8
          - Anvil_RAAS_v4
          - Yehorivka_RAAS_v13
          - Narva_RAAS_v1
          - Kohat_RAAS_v1
          - GooseBay_RAAS_v1
          - Mutaha_RAAS_v2
          - BlackCoast_RAAS_v3
          - Skorpo_RAAS_v4
        ports:
          game: 7787
          query: 27165
          rcon: 21114

      squad_servers:
        - name: "[ASG] Asgard Eternal | New Player Friendly"
          server_id: 1
          docker:
            name: vanilla
            images:
              server: squad:latest
              squadjs: squadjs:latest
          secrets:
            rcon_password: "{{ lookup('ansible.builtin.env', 'SQUAD_RCON_PASSWORD')}}"
            squadjs_discord_token: "{{ lookup('ansible.builtin.env', 'SQUAD_VANILLA_SQUADJS_DISCORD_TOKEN')}}"
            license: "{{ lookup('ansible.builtin.env', 'SQUAD_VANILLA_SERVER_LICENSE')}}"
          ports:
            game: 7789
            query: 27167
            rcon: 21115
          layers:
            - BlackCoast_Invasion_v4
            - Gorodok_Invasion_v3
            - Gorodok_RAAS_v12
            - Harju_RAAS_v6
            - Manicouagan_Invasion_v2
            - Manicouagan_Invasion_v2
            - Yehorivka_RAAS_v13
            - Mestia_Invasion_v2
        - name: "[ASG] Asgard Eternal | Galactic Contention"
          server_id: 4
          docker:
            name: galac
            images:
              server: squad:galac-latest
              squadjs: squadjs:latest

          secrets:
            rcon_password: "{{ lookup('ansible.builtin.env', 'SQUAD_RCON_PASSWORD')}}"
            squadjs_discord_token: "{{ lookup('ansible.builtin.env', 'SQUAD_MEE_SQUADJS_DISCORD_TOKEN')}}"
            license: "{{ lookup('ansible.builtin.env', 'SQUAD_MEE_SERVER_LICENSE')}}"
          ports:
            game: 7787
            query: 27165
            rcon: 21114
          layers:
            - JensensRange_USA-RGF
        - name: "[ASG] Asgard Eternal | Tactical"
          server_id: 3
          docker:
            name: tactical
            images:
              server: squad:tac-latest
              squadjs: squadjs:latest
          secrets:
            rcon_password: "{{ lookup('ansible.builtin.env', 'SQUAD_RCON_PASSWORD')}}"
            squadjs_discord_token: "{{ lookup('ansible.builtin.env', 'SQUAD_TACTICAL_SQUADJS_DISCORD_TOKEN') | default('')}}"
            server_password: "{{ lookup('ansible.builtin.env', 'SQUAD_TACTICAL_SERVER_PASSWORD') | default('')}}"
            license: ""
          remote_admin_list:
            - Einherjar
            - Balder
            - Loki
            - Thor
            - LIAISON
            - Asgard%20Tactical%20INF
            - Asgard%20Event%20Team
          ports:
            game: 7791
            query: 27169
            rcon: 21116
          layers:
            - Harju_RAAS_V6
            - Narva_RAAS_v2
            - Fallujah_RAAS_v5
            - Gorodok_RAAS_v12
            - Belaya_RAAS_v1
            - AlBasrah_Invasion_v7
            - Yehorivka_RAAS_v08
            - Mutaha_RAAS_v6
            - Skorpo_RAAS_v4
            - Gorodok_RAAS_v01
            - Chora_RAAS_v4
            - Yehorivka_Invasion_v1
      registry_site: asgard.orion-technologies.io
      registry_site_email: price@orion-technologies.io
      registry_system_user: docker-reg
      registry_login_user: asgard
      docker_registry_password: "{{ lookup('ansible.builtin.env', 'DOCKER_REGISTRY_PASSWORD') }}"
      superusers:
        - username: asgard
          public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHssdZ0i4vmFOWy49WmPujVEadMBxI+UvGJvFZwpziw+ sam@orion
            - sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAINvi+FdQSbfTLQ9VPHggyjRGeNelQDoGWlwYAmO4AO67AAAABHNzaDo= sam@orion-fido
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFhyEqrO6GViZGUNNgobKYRI/rnc5NqTxUZrVWL9TSYV kinsher@asg
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILnF/FetuAprot8KjSIjod/kuJblCoZzS9xKJLz3TA/N skillet@skillet-laptop
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHssdZ0i4vmFOWy49WmPujVEadMBxI+UvGJvFZwpziw+ github@actions
