---
# yamllint disable rule:line-length
all:
  vars:
    server_timezone: America/Chicago
  hosts:
    asgard-eternal.com:
      ansible_user: asgard
      squad_server_user: asgard
      squad_server_group: asgard
      squad_mysql:
        user: "squadjs"
        user_password: "{{ lookup('ansible.builtin.env', 'SQUAD_MYSQL_USER_PASSWORD' )}}"
        root_password: "{{ lookup('ansible.builtin.env', 'SQUAD_MYSQL_ROOT_PASSWORD' )}}"
        database: squadjs

      squad_default_settings:
        server_id: 0 # As a note, server IDs must be started at 1!
        docker:
          name: vanilla-squad
          images:
            server: squad:latest
            squadjs: squadjs:latest
        secrets:
          rcon_password: test
          squadjs_discord_token: ""
          license: ""
        groups:
          # This is for the discord admin ping
          - name: 1039155511066636329
            permissions: []
            members: []
            squadjs:
              admin_ping: true

          - name: Odin
            permissions:
              - changemap
              - pause
              - balance
              - chat
              - kick
              - ban
              - cameraman
              - teamchange
              - forceteamchange
              - canseeadminchat
              - reserve
              - config
              - cheat
              - featuretest
              - clientdemos
            squadjs:
              admin_ping: false
            members:
              - name: Kinsher
                comment: Server Administrator
                steam64: 76561197986710399

              - name: Atrocity
                steam64: 76561199101367413

              - name: Xikky
                steam64: 76561198001193856

              - name: iiTherRealMcCoy
                steam64: 76561199028579724

              - name: MaxRecon
                steam64: 76561198153769543

              - name: SheHulk
                steam64: 76561198067016254

              - name: wolf.rayne
                steam64: 76561198107367726

              - name: Pears
                steam64: 76561198010920870

          - name: Thor
            squadjs:
              admin_ping: false
            permissions:
              - changemap
              - balance
              - chat
              - kick
              - ban
              - cameraman
              - teamchange
              - forceteamchange
              - canseeadminchat
              - reserve
              - clientdemos
            members:
              - name: Lt_Longsword
                steam64: 76561198373523022

              - name: Freeman
                steam64: 76561198329170534

              - name: Elon
                steam64: 76561198203568744

              - name: Chemji
                steam64: 76561199127559778

              - name: Skillet
                comment: promoted 04-25-23
                steam64: 76561198221715432

          - name: Loki
            squadjs:
              admin_ping: false
            permissions:
              - balance
              - chat
              - kick
              - ban
              - teamchange
              - canseeadminchat
              - reserve
              - cameraman
              - changemap
              - forceteamchange
            members:
              - name: Frizz
                steam64: 76561198339174737

              - name: Dr.hammerstien
                comment: promoted 04-25-2023
                steam64: 76561198037486479

              - name: Rarg
                comment: promoted 4-25-2023
                steam64: 76561198073565669

              - name: Vaunt
                comment: promoted 4-25-2023
                steam64: 76561198031865730

              - name: RIOTYouth1
                comment: Admin 4-27-2023
                steam64: 76561198209119887

              - name: Shifty
                comment: Jr Admin 4-26-2023
                steam64: 76561198251723570

          - name: Balder
            squadjs:
              admin_ping: false
            permissions:
              - balance
              - chat
              - kick
              - ban
              - teamchange
              - canseeadminchat
              - reserve
            members:
              - name: "{ASG} FItzReigN"
                comment: Gdawgeo2@gmail.com
                steam64: 76561199225787710

          - name: Whitelist
            permissions:
              - reserve
            members:
              - name: Gel The Doctor
                comment: Added by MaX unlimited Whitelist
                steam64: 76561198098735539

              - name: Mauro
                comment: men1995@gmail.com
                steam64: 76561198098391966

              - name: RIOTYouth1
                comment: aclerc1220@gmail.com
                steam64: 76561198209119887

              - name: "{ASG} Scarface"
                comment: logangrimes11@gmail.com
                steam64: 76561198312514319

              - name: "{ASG} young sloth"
                comment: logangrimes11@gmail.com
                steam64: 76561198983371735

              - name: Skillet
                comment: Server Administrator
                steam64: 76561198221715432

              - name: LtJamesFox
                steam64: 76561198026192477
                comment: Nevetsu@hotmail.com

              - name: tcandan88(4skin)
                comment: ducati979@aol.com
                steam64: 76561198059124010

              - name: Dick Deflator
                comment: Whitelist for 4 months started 03/11/2023/Ends 07/11/2023
                steam64: 76561199062085282

              - name: Bagels
                comment: adroessler10@gmail.com
                steam64: 76561198059462064

              - name: Hypothermiack
                steam64: 76561198119385943

              - name: TapatioTimmy
                comment: camdenricketts4@gmail.com
                steam64: 76561199123384670

              - name: TheGoochSlooth
                comment: justintestorelli@gmail.com
                steam64: 76561199285813056

              - name: Subterfuge
                comment: jwlind@gmail.com
                steam64: 76561197963075020

              - name: Juggernaut
                comment: robledoaustin@yahoo.com
                steam64: 76561198049739312

              - name: DamiSupreme
                comment: alexdemiane93@gmail.com
                steam64: 76561197979663830

              - name: Mr_poopy_diaper
                comment: Attached to (ASG) Kybar (carbarykyle@gmail.com)
                steam64: 76561199302780874

              - name: OneBarStatus
                comment: jacobadams135@yahoo.com
                steam64: 76561198801895406

              - name: Kazy
                comment: jacobadams135@yahoo.com (Attached to OneBarStatus)
                steam64: 76561198989641003

              - name: The Half-WitViking
                comment: jacobadams135@yahoo.com (Attached to OneBarStatus)
                steam64: 76561198870442236

              - name: Warbot
                comment: imawsome404@yahoo.com - Xikky
                steam64: 76561197960350874

              - name: Duffmann9992
                comment: Attached to imawsome404@yahoo.com - xikky
                steam64: 76561197986254647

              - name: HeyWhatchaDoin
                comment: Attached to imawsome404@yahoo.com - Xikky
                steam64: 76561198405495371

              - name: Buckwheat10
                comment: attached to imawsome404@yahoo.com - Xikky
                steam64: 76561198056113440

              - name: BoozBear
                comment: attached to imawsome404@yahoo.com - Xikky
                steam64: 76561198940959919

              - name: dmpca
                comment: attached to imawsome404@yahoo.com - Xikky
                steam64: 76561197962791616

              - name: fonzie141
                comment: benmandino@gmail.com
                steam64: 76561198056302525

              - name: "Orion159044#1238 @T/5 Fairchild [29th ID]"
                comment: orionbarclay7@gmail.com
                steam64: 76561198170375391

              - name: "[NOT]TheSaltiestAround"
                comment: austinbuda99@gmail.com
                steam64: 76561198107206903

              - name: "1stRB NinjaOfDeath"
                comment: Added by MaX
                steam64: 76561198386944513

              - name: someoneulove
                steam64: 76561198073942737

              - name: Malinoff
                steam64: 76561198404402665

              - name: SooperGloo
                steam64: 76561198855097026

        ban_urls: []
        remote_admin_hosts: []
        remote_admin_list:
          - vanilla-autowl
          - Einherjar
          - Balder
          - Loki
          - Thor
          - LIAISON
          - ASG Champions Of The Month
          - expats
          - ASG Affiliates
          - Elevated Seeding Perms
          - Active Whitelist
        messages:
        vote:
          FirstLayer: JensensRange_USA-RGF
          TeamVote_Duration: 20
          LayerVoteDuration: 20
        seed_layers:
          - AlBasrah_Seed_v1
          - BlackCoast_Seed_v1
          - BlackCoast_Seed_v2
          - Fallujah_Seed_v1
          - Harju_Seed_v1
          - Logar_Seed_v1
          - Manicouagan_Seed_v1
          - Mutaha_Seed_v1
          - Sanxian_Seed_v1
          - Sumari_Seed_v1
        layers:
          - Gorodok_RAAS_v7
          - AlBasrah_Invasion_v1
          - AlBasrah_Invasion_v2
          - AlBasrah_RAAS_v1
          - Anvil_Invasion_v1
          - Anvil_RAAS_v1
          - Anvil_RAAS_v2
          - Belaya_Invasion_v1
          - Belaya_Invasion_v2
          - Belaya_RAAS_v1
          - BlackCoast_Invasion_v1
          - BlackCoast_Invasion_v2
          - BlackCoast_RAAS_v1
          - BlackCoast_RAAS_v2
          - Chora_Invasion_v1
          - Chora_Invasion_v2
          - Chora_RAAS_v1
          - Fallujah_Invasion_v1
          - Fallujah_Invasion_v2
          - Fallujah_RAAS_v1
          - Fallujah_RAAS_v2
          - FoolsRoad_Invasion_v1
          - FoolsRoad_RAAS_v1
          - FoolsRoad_RAAS_v2
          - FoolsRoad_RAAS_v3
          - GooseBay_Invasion_v1
          - GooseBay_RAAS_v1
          - GooseBay_RAAS_v2
          - Gorodok_Invasion_v1
          - Gorodok_Invasion_v2
          - Gorodok_RAAS_v1
          - Gorodok_RAAS_v2
          - Harju_Invasion_v1
          - Harju_Invasion_v2
          - Harju_Invasion_v3
          - Harju_RAAS_v1
          - Harju_RAAS_v2
          - Kamdesh_Invasion_v1
          - Kamdesh_RAAS_v1
          - Kohat_RAAS_v1
          - Kohat_Invasion_v1
          - Kokan_Invasion_v1
          - Kokan_RAAS_v1
          - Kokan_RAAS_v2
          - Lashkar_Invasion_v1
          - Lashkar_RAAS_v1
          - Logar_RAAS_v1
          - Manicouagan_RAAS_v1
          - Manicouagan_RAAS_v2
          - Manicouagan_Invasion_v1
          - Mestia_Invasion_v1
          - Mestia_RAAS_v1
          - Mutaha_Invasion_v1
          - Mutaha_RAAS_v1
          - Mutaha_RAAS_v2
          - Narva_Invasion_v1
          - Narva_Invasion_v2
          - Narva_RAAS_v1
          - Sanxian_Invasion_v1
          - Sanxian_Invasion_v2
          - Sanxian_RAAS_v1
          - Sanxian_RAAS_v2
          - Skorpo_Invasion_v1
          - Skorpo_Invasion_v2
          - Skorpo_RAAS_v1
          - Sumari_Invasion_v1
          - Sumari_RAAS_v1
          - Tallil_Invasion_v1
          - Tallil_RAAS_v1
          - Tallil_RAAS_v2
          - Yehorivka_Invasion_v1
          - Yehorivka_Invasion_v2
          - Yehorivka_RAAS_v1
          - Yehorivka_RAAS_v2
        ports:
          game: 7787
          query: 27165
          rcon: 21114
          beacon: 15000

      squad_servers:
        - name: "[ASG] Asgard Eternal | New Player Friendly"
          server_id: 1
          docker:
            name: vanilla
            images:
              server: squad:latest
              squadjs: squadjs:latest
          secrets:
            rcon_password: "{{ lookup('ansible.builtin.env', 'SQUAD_RCON_PASSWORD')}}"
            squadjs_discord_token: "{{ lookup('ansible.builtin.env', 'SQUAD_VANILLA_SQUADJS_DISCORD_TOKEN')}}"
            license: "{{ lookup('ansible.builtin.env', 'SQUAD_VANILLA_SERVER_LICENSE')}}"
          ports:
            game: 7787
            query: 27165
            rcon: 21114
            beacon: 15100
        - name: "[ASG] Asgard Eternal | Tactical"
          server_id: 3
          tk_auto_kick_enabled: false
          prevent_team_change_if_unbalanced: false
          docker:
            name: tactical
            images:
              server: squad:tac-latest
              squadjs: squadjs:latest
          secrets:
            rcon_password: "{{ lookup('ansible.builtin.env', 'SQUAD_RCON_PASSWORD')}}"
            squadjs_discord_token: "{{ lookup('ansible.builtin.env', 'SQUAD_TACTICAL_SQUADJS_DISCORD_TOKEN') | default('')}}"
            server_password: "{{ lookup('ansible.builtin.env', 'SQUAD_TACTICAL_SERVER_PASSWORD') | default('')}}"
            license: ""
          remote_admin_list:
            - Einherjar
            - Balder
            - Loki
            - Thor
            - LIAISON
            - Asgard Tactical INF
            - Asgard Event Team
          ports:
            game: 7791
            query: 27169
            rcon: 21116
            beacon: 15200
      registry_site: asgard-eternal.com
      registry_site_email: price@orion-technologies.io
      registry_system_user: docker-reg
      registry_login_user: asgard
      docker_registry_password: "{{ lookup('ansible.builtin.env', 'DOCKER_REGISTRY_PASSWORD') }}"
      superusers:
        - username: asgard
          public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOkWsSntg1ufF40cALcIBA7WZhiU/f0cncqq0pcp+DZY openpgp:0x15993C90 sam@orion # Sam's ssh key
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFhyEqrO6GViZGUNNgobKYRI/rnc5NqTxUZrVWL9TSYV kinsher@asg # Kinsher's SSH Key
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILnF/FetuAprot8KjSIjod/kuJblCoZzS9xKJLz3TA/N skillet@skillet-laptop # Skillet's SSH Key
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHssdZ0i4vmFOWy49WmPujVEadMBxI+UvGJvFZwpziw+ github@actions
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBrZWc/sqksZ5X4kUfqGHimLJx6KPqipgBVBXXnZMmhi bcrfo@BCR-SHB # Max Recon's  SSH Key
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFXaLeb1zZ4Pz4MLoGvk9RzTjsXP2aTWjnFN8kf/DeYq kscop@HomePC # Xikky's SSH Key
