all:
  vars:
    server_timezone: America/Chicago
  hosts:
    asgard.orion-technologies.io:
      ansible_user: asgard
      squad_server_user: asgard
      squad_server_group: asgard
      squad_default_settings:
        docker:
          name: vanilla-squad
          images:
            server: squad:latest
            squadjs: squadjs:latest
        secrets:
          rcon_password: test
          squadjs_discord_token: ""
          license: ""
        groups:
          # This is for the discord admin ping
          - name: 1039155511066636329
            permissions: []
            squadjs:
              admin_ping: true

          - name: Odin
            permissions:
              - changemap
              - pause
              - balance
              - chat
              - kick
              - ban
              - cameraman
              - teamchange
              - forceteamchange
              - canseeadminchat
              - reserve
              - config
            squadjs:
              admin_ping: true
            members:
              - name: Kinsher
                comment: Server Administrator
                steam64: 76561197986710399

              - name: Atrocity
                steam64: 76561199101367413

              - name: Xikky
                steam64: 76561198001193856

              - name: iiTherRealMcCoy
                steam64: 76561199028579724

              - name: MaxRecon
                steam64: 76561198153769543

              - name: SheHulk
                steam64: 76561198067016254

              - name: Malinoff
                steam64: 76561198404402665

              - name: Someoneulove
                steam64: 76561198073942737

              - name: Teggy
                steam64: 76561198356666755

              - name: SooperGloo
                steam64: 76561198855097026

          - name: SrAdmin
            squadjs:
              admin_ping: true
            permissions:
              - changemap
              - balance
              - chat
              - kick
              - ban
              - cameraman
              - teamchange
              - forceteamchange
              - canseeadminchat
              - reserve
            members:
              - name: Frizz
                steam64: 76561198339174737

              - name: Lt_Longsword
                steam64: 76561198373523022

              - name: Buddy
                steam64: 76561199201845769

              - name: Ray
                steam64: 76561198015328506

              - name: Freeman
                steam64: 76561198329170534

              - name: Omega
                steam64: 76561199018771290

              - name: Coiffee
                steam64: 76561198046579272

              - name: Elon
                steam64: 76561198203568744

              - name: Kin_Seward
                steam64: 76561198799111045

              - name: RangerSix
                steam64: 76561198206734757

              - name: Epimetheus
                steam64: 76561199094282718

              - name: Chemji
                steam64: 76561199127559778

              - name: Mirage40K
                steam64: 76561198059250541

              - name: Rabbid_Squirrel
                steam64: 76561198081576045

              - name: Sweetwater
                steam64: 76561198124658412

              - name: wolf.rayne
                steam64: 76561198107367726

          - name: JrAdmin
            squadjs:
              admin_ping: true
            permissions:
              - balance
              - chat
              - kick
              - ban
              - teamchange
              - canseeadminchat
              - reserve
            members:
              - name: Sexo
                comment: Primary Seeder
                steam64: 76561198003130199

          - name: Whitelist
            permissions:
              - reserve
            members:
              - name: Treay ~ Sam
                comment: For Asgard IT Started 01/09/2023
                steam64: 76561198090760895

              - name: Trippy Chivas
                comment: devbryanbar@gmail.com
                steam64: 76561198106004468

              - name: RIOTYouth1
                comment: aclerc1220@gmail.com
                steam64: 76561198209119887

              - name: "{ASG} Scarface"
                comment: logangrimes11@gmail.com
                steam64: 76561198312514319

              - name: "{ASG} young sloth"
                comment: logangrimes11@gmail.com
                steam64: 76561198983371735

              - name: Skillet
                comment: Server Administrator
                steam64: 76561198221715432

              - name: LtJamesFox
                steam64: 76561198026192477
                comment: Nevetsu@hotmail.com

              - name: tcandan88(4skin)
                comment: ducati979@aol.com
                steam64: 76561198059124010

              - name: Dick Deflator
                comment: Granted Whitelist for 3 month's started 12/01/2022/Ends 02/28/2023
                steam64: 76561199062085282

              - name: Bagels
                comment: adroessler10@gmail.com
                steam64: 76561198059462064

              - name: Hypothermiack
                steam64: 76561198119385943

              - name: TapatioTimmy
                comment: camdenricketts4@gmail.com
                steam64: 76561199123384670

              - name: TheGoochSlooth
                comment: justintestorelli@gmail.com
                steam64: 76561199285813056

              - name: Subterfuge
                comment: jwlind@gmail.com
                steam64: 76561197963075020

              - name: Kybar
                comment: carbarykyle@gmail.com
                steam64: 76561198128034210

              - name: Juggernaut
                comment: robledoaustin@yahoo.com
                steam64: 76561198049739312

              - name: DamiSupreme
                comment: alexdemiane93@gmail.com
                steam64: 76561197979663830

              - name: Dang Li Wang
                comment: n.hinesly0602@gmail.com
                steam64: 76561199241025555

              - name: Jenna Tools
                comment: n.hinesly0602@gmail.com
                steam64: 76561199241627472

              - name: Mr_poopy_diaper
                comment: Attached to (ASG) Kybar (carbarykyle@gmail.com)
                steam64: 76561199302780874

              - name: OneBarStatus
                comment: jacobadams135@yahoo.com
                steam64: 76561198801895406

          - name: CAS
            permissions:
              - reserve
            members:
              - name: Albertime
                comment: CAS
                steam64: 7656119844551138

              - name: JF
                comment: CAS
                steam64: 76561198094918611

              - name: Jashy
                comment: CAS
                steam64: 76561198153409985

              - name: Oscar
                comment: CAS
                steam64: 76561198150626482

              - name: Skay
                comment: CAS
                steam64: 76561198248146940

          - name: HC
            permissions:
              - reserve
            members:
              - name: Sir Peabody
                comment: HC
                steam64: 76561198043032389

              - name: Kameron
                comment: HC
                steam64: 76561197982328479

              - name: Evans
                comment: HC
                steam64: 76561198101099268

              - name: Brodizle
                comment: HC
                steam64: 76561198249614886

              - name: Skeebler
                comment: HC
                steam64: 76561198191984002

          - name: SLT
            permissions:
              - reserve
            members:
              - name: EnderDevs
                comment: SLT
                steam64: 76561198149412908

              - name: JoeBrandonCheated
                comment: SLT
                steam64: 76561198448114730

          - name: BR1
            permissions:
              - reserve
            members:
              - name: Madtopher
                comment: BR1
                steam64: 76561199060693600

              - name: Dr. Hammerstein
                comment: BR1
                steam64: 76561198037486479

              - name: Bags
                comment: BR1
                steam64: 76561198315718944

        ban_urls: []
        remote_admin_hosts: []
        messages:
          - Welcome to Asgard Eternal! Remember to add Asgard to your favorites list!!
          - Check out Asgard Discord https://discord.gg/asg
        layers:
          - Kohat_RAAS_v9
          - Mutaha_RAAS_v1
          - Narva_Invasion_v1
          - Yehorivka_RAAS_v01
          - BlackCoast_RAAS_v4
          - Gorodok_RAAS_v07
          - Tallil_RAAS_v5
          - Skorpo_RAAS_v5
          - Narva_RAAS_v4
          - Gorodok_RAAS_v09
        ports:
          game: 7787
          query: 27165
          rcon: 21114

      squad_servers:
        - name: "[ASG] Asgard Eternal | New Player Friendly"
          docker:
            name: vanilla
            images:
              server: squad:latest
              squadjs: squadjs:latest
          secrets:
            rcon_password: "{{ lookup('ansible.builtin.env', 'SQUAD_RCON_PASSWORD')}}"
            squadjs_discord_token: "{{ lookup('ansible.builtin.env', 'SQUAD_VANILLA_SQUADJS_DISCORD_TOKEN')}}"
            license: "{{ lookup('ansible.builtin.env', 'SQUAD_VANILLA_SERVER_LICENSE')}}"
          ports:
            game: 7789
            query: 27167
            rcon: 21115
          layers:
            - Gorodok_RAAS_v07
            - Mutaha_RAAS_v1
            - Narva_Invasion_v1
            - BlackCoast_RAAS_v4
            - Skorpo_RAAS_v5
            - Gorodok_RAAS_v12
            - Tallil_RAAS_v5
            - Yehorivka_RAAS_v01
            - Narva_RAAS_v4
            - Kohat_RAAS_v9

        - name: "[ASG] Asgard Eternal | MEE - New Player Friendly"
          docker:
            name: mee-french
            images:
              server: squad:mee-french-latest
              squadjs: squadjs:latest

          secrets:
            rcon_password: "{{ lookup('ansible.builtin.env', 'SQUAD_RCON_PASSWORD')}}"
            squadjs_discord_token: "{{ lookup('ansible.builtin.env', 'SQUAD_MEE_SQUADJS_DISCORD_TOKEN')}}"
            license: "{{ lookup('ansible.builtin.env', 'SQUAD_MEE_SERVER_LICENSE')}}"
          ports:
            game: 7787
            query: 27165
            rcon: 21114
          layers:
            - JensensRange_USA-RUS
            - MEE_BlackCoast_RAAS_v1_USMC20vWAG
            - MEE_Fallujah_Invasion_v3_USMC20vIRN
            - MEE_Narva_Invasion_v1_POLvWAG
            - MEE_Gorodok_RAAS_v1_HRvWAG
            - MEE_Tallil_Outskirts_Invasion_v3_TAFvIRGC
            - MEE_Lashkar_Valley_Invasion_v4_ADFvMEINS
            - MEE_Gorodok_RAAS_v2_75vWAG
            - MEE_Island_Invasion_v1_PIMAvTAF
            - MEE_Narva_RAAS_v1_POLvWAG
            - MEE_Fallujah_AAS_v1_GDvMEINS
      registry_site: asgard.orion-technologies.io
      registry_site_email: price@orion-technologies.io
      registry_system_user: docker-reg
      registry_login_user: asgard
      docker_registry_password: "{{ lookup('ansible.builtin.env', 'DOCKER_REGISTRY_PASSWORD') }}"
      superusers:
        - username: asgard
          public_keys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHssdZ0i4vmFOWy49WmPujVEadMBxI+UvGJvFZwpziw+ sam@orion
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFhyEqrO6GViZGUNNgobKYRI/rnc5NqTxUZrVWL9TSYV kinsher@asg
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP7P1Cm+zltA135iFnS7rvf9YlfELjuX1YIgSm9HA5f0 skillet@skillet-laptop
