---
- name: Setup Server
  hosts: all
  pre_tasks:
    - name: Update Caches
      become: true
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: initial-setup
      tags:
        - initial
    - role: docker
      tags:
        - docker
