---
# handlers file for initial-setup
- name: Restart systemd-resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  listen:
    - Restart systemd-resolved

- name: Enable NTP
  become: true
  ansible.builtin.command: timedatectl set-ntp on
  listen:
    - Enable NTP

- name: Restart SSHD
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen:
    - Restart SSHD
