name: Build Docker Image

on:
  workflow_call:

jobs:

  build:

    runs-on: self-hosted

    steps:
    
    - name: clean work directory
      uses: AutoModality/action-clean@v1
    
    - name: checkout repo
      uses: actions/checkout@v3
      with:
        path: dev
    
    - name: check files
      run: cd dev/

    - name: Login To Registry
      uses: docker/login-action@v2
      with:
        registry: "${{ vars.DOCKER_REGISTRY_URL }}"
        username: "${{ secrets.DOCKER_REGISTRY_USER }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Ansible Image
      uses: docker/build-push-action@v3
      with:
        context: ./dev
        file: ./Dockerfile
        push: true
        cache-from: type=registry,ref=${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.ansible_container }}:latest
        cache-to: type=inline
        tags: "${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.ansible_container }}:latest"
