name: Build Docker Image

on:
  workflow_call:
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Login To Registry
        uses: docker/login-action@v3
        with:
          registry: "${{ vars.DOCKER_REGISTRY_URL }}"
          username: "${{ secrets.DOCKER_REGISTRY_USER }}"
          password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Ansible Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.ANSIBLE_CONTAINER }}:latest"

