name: Update Squad Configurations

on:
  workflow_dispatch:

jobs:

  build-image:
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit

  deploy:
    runs-on: self-hosted
    needs:
      - build-image
    container:
      image: ${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.ansible_container }}:latest
      credentials:
        username: "${{ secrets.DOCKER_REGISTRY_USER }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
      env:
        SQUAD_RCON_PASSWORD: "${{ secrets.squad_rcon_password }}"

        SQUAD_VANILLA_SERVER_LICENSE: "${{ secrets.squad_vanilla_server_license }}"
        SQUAD_VANILLA_SQUADJS_DISCORD_TOKEN: "${{ secrets.squad_vanilla_squadjs_discord_token }}"

        SQUAD_MEE_SERVER_LICENSE: "${{ secrets.squad_mee_server_license }}"
        SQUAD_MEE_SQUADJS_DISCORD_TOKEN: "${{ secrets.squad_mee_squadjs_discord_token }}"


    steps:
      - name: Inject Private Key
        run: |
          mkdir -p "${HOME}/.ssh"

          cat << __EOF__ > "${HOME}/.ssh/key"
          ${{ secrets.ansible_ssh_key }}
          __EOF__

          chmod 0600 "${HOME}/.ssh/key"

          cat << __EOF__ > "${HOME}/.ssh/config"
          Host *
              User ${{ vars.ssh_user }}
              StrictHostKeyChecking no

          Host ${{ vars.server_host }}
              HostName ${{ vars.server_host }}
              User ${{ vars.ssh_user }}
              IdentityFile ~/.ssh/key
          __EOF__

      - name: Run Ansible Playbook For Squad
        run: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook playbook.yml --tags=squad
