name: Lint Inventory

on:
  workflow_call:

jobs:
  build-image:
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit

  lint-inventory:
    runs-on: self-hosted
    needs: build-image
    container:
      image: ${{ vars.DOCKER_REGISTRY_URL }}/${{ vars.ansible_container }}:latest
      credentials:
        username: "${{ secrets.DOCKER_REGISTRY_USER }}"
        password: "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"


    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Lint Inventory
        run: |
          yamllint -d "{extends: default, rules: {trailing-spaces: {level: warning}, comments: { min-spaces-from-content: 1}}}" ./inventory.yml
